[build]
  base = "/"  # Adjust this if your project is in a subfolder
  command = "pip install -r requirements.txt"  # Install dependencies
  publish = "/"  # Or specify the correct directory, typically the root for single-page apps

[functions]
  directory = "functions"  # Netlify will look for Python functions here

[redirects]
  # Redirect all traffic to index.html (useful for Single Page Applications)
  from = "/"
  to = "/index.html"
  status = 200
