[build]
  base = "/"  # Base directory where your code is located (root directory)
  command = "pip install -r requirements.txt"  # Install Python dependencies
  publish = "public"  # Publish directory for static content (if you have any)

[functions]
  directory = "functions"  # This points to the folder containing app.py

[[redirects]]
  from = "/"
  to = "/index.html"  # Redirect root to index.html (if you have one)
  status = 200
