[build]
  base = "/"
  command = "pip install -r requirements.txt && python app.py"  # or any appropriate command to start your app
  publish = "static"  # Or wherever your static files are located

[functions]
  directory = "functions"  # If you use serverless functions, otherwise remove this

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200  # Rewrite to serve the index.html if applicable
