[build]
  base = "/"  # or set this to a specific subfolder if needed
  command = "pip install -r requirements.txt"  # to install Python dependencies
  publish = "/"  # Change this to root or the folder containing index.html

[functions]
  directory = "functions"  # Keep this as is, if you're using serverless functions
